language: android
android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-26
    - android-27

    # Additional components

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-addon-google_apis-google-26
    - sys-img-armeabi-v7a-android-27

    # Support library
    - extra-android-support
    
  licenses: 
      - android-sdk-preview-license-.+ 
      - android-sdk-license-.+ 
      - google-gdk-license-.+